---
Name: workflowconfig
After: 'framework/*','cms/*'
---
SiteTree:
    extensions:
        - WorkflowApplicable
CMSPageEditController:
    extensions:
        - AdvancedWorkflowExtension
WorkflowDefinitionExporter:
    exportFormat: YML
    exportMimeType: text/x-yaml
File:
    extensions:
        - FileWorkflowExportExtension
